/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync State */
        get: operations["sync_state_api_sync_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Batch */
        post: operations["sync_batch_api_sync_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Ids */
        post: operations["sync_ids_api_sync_ids_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artwork/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artwork Get */
        get: operations["artwork_get_api_artwork__sha256__get"];
        /** Artwork Put */
        put: operations["artwork_put_api_artwork__sha256__put"];
        post?: never;
        delete?: never;
        options?: never;
        /** Artwork Head */
        head: operations["artwork_head_api_artwork__sha256__head"];
        patch?: never;
        trace?: never;
    };
    "/api/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tracks */
        get: operations["list_tracks_api_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Detail */
        get: operations["track_detail_api_tracks__track_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{track_id}/compatible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compatible Tracks */
        get: operations["compatible_tracks_api_tracks__track_id__compatible_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/facets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Facets */
        get: operations["facets_api_facets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History Sessions */
        get: operations["history_sessions_api_history_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History Session */
        get: operations["history_session_api_history_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Events */
        post: operations["agent_events_api_agent_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live State */
        get: operations["get_live_state_api_live_state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/auto-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Auto Record */
        get: operations["get_auto_record_api_live_auto_record_get"];
        /** Put Auto Record */
        put: operations["put_auto_record_api_live_auto_record_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Ping */
        get: operations["agent_ping_api_agent_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sets */
        get: operations["list_sets_api_sets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Set */
        post: operations["start_set_api_sets_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/{set_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop Set */
        post: operations["stop_set_api_sets__set_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/{set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Set */
        get: operations["get_set_api_sets__set_id__get"];
        put?: never;
        post?: never;
        /** Delete Set */
        delete: operations["delete_set_api_sets__set_id__delete"];
        options?: never;
        head?: never;
        /** Patch Set */
        patch: operations["patch_set_api_sets__set_id__patch"];
        trace?: never;
    };
    "/api/sets/{set_id}/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Entry */
        delete: operations["delete_entry_api_sets__set_id__entries__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/transitions/{transition_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Transition */
        patch: operations["patch_transition_api_transitions__transition_id__patch"];
        trace?: never;
    };
    "/api/sets/import-rb/{history_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Rb */
        post: operations["import_rb_api_sets_import_rb__history_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sets/import-rb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Rb All */
        post: operations["import_rb_all_api_sets_import_rb_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveSet */
        ActiveSet: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Source */
            source?: string | null;
            /**
             * Auto
             * @default false
             */
            auto: boolean;
        };
        /** AgentStatus */
        AgentStatus: {
            /** Connected */
            connected: boolean;
            /** Hostname */
            hostname?: string | null;
            /** Rb Version */
            rb_version?: string | null;
            /** Last Seen */
            last_seen?: string | null;
        };
        /** AutoRecordOut */
        AutoRecordOut: {
            /** Auto Record */
            auto_record: boolean;
        };
        /** BatchResult */
        BatchResult: {
            /**
             * Entity
             * @enum {string}
             */
            entity: "tracks" | "cues" | "my_tags" | "track_my_tags" | "playlists" | "playlist_entries" | "history_sessions" | "history_entries";
            /** Upserted */
            upserted: number;
            /** Deleted */
            deleted: number;
        };
        /** Cue */
        Cue: {
            /** Id */
            id: string;
            /** Content Id */
            content_id: string;
            /** Kind */
            kind?: number | null;
            /** In Ms */
            in_ms?: number | null;
            /** Out Ms */
            out_ms?: number | null;
            /** Color */
            color?: number | null;
            /** Comment */
            comment?: string | null;
            /** Rb Local Usn */
            rb_local_usn?: number | null;
        };
        /** FacetItem */
        FacetItem: {
            /** Id */
            id?: string | null;
            /** Name */
            name?: string | null;
            /** Count */
            count: number;
        };
        /** Facets */
        Facets: {
            /** Genres */
            genres: components["schemas"]["FacetItem"][];
            /** Camelots */
            camelots: components["schemas"]["FacetItem"][];
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["FacetItem"][];
            /** My Tags */
            my_tags: components["schemas"]["TagNode"][];
            /** Playlists */
            playlists: components["schemas"]["PlaylistNode"][];
            /** Bpm Min */
            bpm_min?: number | null;
            /** Bpm Max */
            bpm_max?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistoryEntryOut */
        HistoryEntryOut: {
            /** Id */
            id: string;
            /** History Id */
            history_id: string;
            /** History Name */
            history_name?: string | null;
            /** History Date */
            history_date?: string | null;
            /** Content Id */
            content_id: string;
            /** Track No */
            track_no?: number | null;
            /** Created At */
            created_at?: string | null;
            track?: components["schemas"]["TrackOut"] | null;
        };
        /** IdSet */
        IdSet: {
            /**
             * Entity
             * @enum {string}
             */
            entity: "tracks" | "cues" | "my_tags" | "track_my_tags" | "playlists" | "playlist_entries" | "history_sessions" | "history_entries";
            /** Ids */
            ids: string[];
        };
        /** IdSetResult */
        IdSetResult: {
            /**
             * Entity
             * @enum {string}
             */
            entity: "tracks" | "cues" | "my_tags" | "track_my_tags" | "playlists" | "playlist_entries" | "history_sessions" | "history_entries";
            /** Deleted */
            deleted: number;
        };
        /** ImportAllResult */
        ImportAllResult: {
            /** Imported */
            imported: number;
            /** Skipped Already Imported */
            skipped_already_imported: number;
            /** Skipped Already Live */
            skipped_already_live: number;
            /** Results */
            results: components["schemas"]["ImportResult"][];
        };
        /** ImportResult */
        ImportResult: {
            /** Set Id */
            set_id?: number | null;
            /**
             * Already Imported
             * @default false
             */
            already_imported: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /** Reason */
            reason?: string | null;
            /** History Id */
            history_id?: string | null;
        };
        /** LiveState */
        LiveState: {
            agent: components["schemas"]["AgentStatus"];
            now_playing?: components["schemas"]["TrackSummary"] | null;
            /** Now Playing At */
            now_playing_at?: string | null;
            /**
             * Session
             * @default []
             */
            session: components["schemas"]["SessionItem"][];
            active_set?: components["schemas"]["ActiveSet"] | null;
            /**
             * Auto Record
             * @default true
             */
            auto_record: boolean;
            /**
             * Suggestions
             * @default []
             */
            suggestions: components["schemas"]["Suggestion"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Authenticated */
            authenticated: boolean;
        };
        /** MyTag */
        MyTag: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Rb Local Usn */
            rb_local_usn?: number | null;
        };
        /** PlayEvent */
        PlayEvent: {
            /** History Entry Id */
            history_entry_id: string;
            /** History Id */
            history_id: string;
            /** Content Id */
            content_id: string;
            /** Played At */
            played_at?: string | null;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            track?: components["schemas"]["Track"] | null;
        };
        /** PlaylistNode */
        PlaylistNode: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /**
             * Is Folder
             * @default false
             */
            is_folder: boolean;
            /**
             * Is Smart
             * @default false
             */
            is_smart: boolean;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["PlaylistNode"][];
        };
        /** PlaylistRef */
        PlaylistRef: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Parent Id */
            parent_id?: string | null;
            /** Track No */
            track_no?: number | null;
        };
        /** Reason */
        Reason: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
            /** Value */
            value?: number | null;
        };
        /** SessionDetail */
        SessionDetail: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Date Created */
            date_created?: string | null;
            /** Entry Count */
            entry_count: number;
            /** Entries */
            entries: components["schemas"]["HistoryEntryOut"][];
        };
        /** SessionItem */
        SessionItem: {
            track: components["schemas"]["TrackSummary"] | null;
            /** Played At */
            played_at?: string | null;
        };
        /** SessionOut */
        SessionOut: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /** Date Created */
            date_created?: string | null;
            /** Entry Count */
            entry_count: number;
        };
        /** SetDetail */
        SetDetail: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /** Source */
            source?: string | null;
            /** Rb History Id */
            rb_history_id?: string | null;
            /**
             * Auto
             * @default false
             */
            auto: boolean;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Entry Count
             * @default 0
             */
            entry_count: number;
            /** Duration S */
            duration_s?: number | null;
            /**
             * Fav Count
             * @default 0
             */
            fav_count: number;
            /** Notes */
            notes?: string | null;
            /**
             * Entries
             * @default []
             */
            entries: components["schemas"]["SetEntryOut"][];
            /**
             * Transitions
             * @default []
             */
            transitions: components["schemas"]["TransitionOut"][];
        };
        /** SetEntryOut */
        SetEntryOut: {
            /** Id */
            id: number;
            /** Position */
            position: number;
            /** Track Id */
            track_id?: string | null;
            /** Played At */
            played_at?: string | null;
            /** Offset Seconds */
            offset_seconds?: number | null;
            /** Rb History Entry Id */
            rb_history_entry_id?: string | null;
            track?: components["schemas"]["TrackSummary"] | null;
        };
        /** SetOut */
        SetOut: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /** Source */
            source?: string | null;
            /** Rb History Id */
            rb_history_id?: string | null;
            /**
             * Auto
             * @default false
             */
            auto: boolean;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /**
             * Entry Count
             * @default 0
             */
            entry_count: number;
            /** Duration S */
            duration_s?: number | null;
            /**
             * Fav Count
             * @default 0
             */
            fav_count: number;
        };
        /** SetPatch */
        SetPatch: {
            /** Name */
            name?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** SetRef */
        SetRef: {
            /** Id */
            id: number;
            /** Name */
            name?: string | null;
            /** Started At */
            started_at?: string | null;
        };
        /** SetStartRequest */
        SetStartRequest: {
            /** Name */
            name?: string | null;
        };
        /** Suggestion */
        Suggestion: {
            track: components["schemas"]["TrackSummary"];
            /** Score */
            score: number;
            /** Reasons */
            reasons: components["schemas"]["Reason"][];
        };
        /** SyncBatch */
        SyncBatch: {
            /**
             * Entity
             * @enum {string}
             */
            entity: "tracks" | "cues" | "my_tags" | "track_my_tags" | "playlists" | "playlist_entries" | "history_sessions" | "history_entries";
            /** Upserts */
            upserts?: {
                [key: string]: unknown;
            }[];
            /** Deletes */
            deletes?: string[];
            /** Max Usn */
            max_usn?: number | null;
        };
        /** SyncStateResponse */
        SyncStateResponse: {
            /** Entities */
            entities: {
                [key: string]: number | null;
            };
        };
        /** TagNode */
        TagNode: {
            /** Id */
            id: string;
            /** Name */
            name?: string | null;
            /**
             * Children
             * @default []
             */
            children: components["schemas"]["TagNode"][];
        };
        /** Track */
        Track: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Mix */
            mix?: string | null;
            /** Artist Id */
            artist_id?: string | null;
            /** Artist */
            artist?: string | null;
            /** Original Artist Id */
            original_artist_id?: string | null;
            /** Original Artist */
            original_artist?: string | null;
            /** Remixer Id */
            remixer_id?: string | null;
            /** Remixer */
            remixer?: string | null;
            /** Composer Id */
            composer_id?: string | null;
            /** Composer */
            composer?: string | null;
            /** Album Id */
            album_id?: string | null;
            /** Album */
            album?: string | null;
            /** Genre Id */
            genre_id?: string | null;
            /** Genre */
            genre?: string | null;
            /** Label Id */
            label_id?: string | null;
            /** Label */
            label?: string | null;
            /** Key Id */
            key_id?: string | null;
            /** Key Name */
            key_name?: string | null;
            /** Camelot */
            camelot?: string | null;
            /** Bpm */
            bpm?: number | null;
            /** Length S */
            length_s?: number | null;
            /** Rating */
            rating?: number | null;
            /** Color */
            color?: string | null;
            /** Comment */
            comment?: string | null;
            /** Dj Play Count */
            dj_play_count?: number | null;
            /** File Path */
            file_path?: string | null;
            /** File Name */
            file_name?: string | null;
            /** File Type */
            file_type?: number | null;
            /** Bitrate */
            bitrate?: number | null;
            /** Sample Rate */
            sample_rate?: number | null;
            /** Release Year */
            release_year?: number | null;
            /** Release Date */
            release_date?: string | null;
            /** Date Added */
            date_added?: string | null;
            /** Artwork Path */
            artwork_path?: string | null;
            /** Artwork Hash */
            artwork_hash?: string | null;
            /** Rb Local Usn */
            rb_local_usn?: number | null;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Deleted
             * @default false
             */
            deleted: boolean;
        };
        /** TrackDetail */
        TrackDetail: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Mix */
            mix?: string | null;
            /** Artist */
            artist?: string | null;
            /** Original Artist */
            original_artist?: string | null;
            /** Remixer */
            remixer?: string | null;
            /** Composer */
            composer?: string | null;
            /** Album */
            album?: string | null;
            /** Genre */
            genre?: string | null;
            /** Label */
            label?: string | null;
            /** Key Name */
            key_name?: string | null;
            /** Camelot */
            camelot?: string | null;
            /** Bpm */
            bpm?: number | null;
            /** Length S */
            length_s?: number | null;
            /** Rating */
            rating?: number | null;
            /** Color */
            color?: string | null;
            /** Comment */
            comment?: string | null;
            /** Play Count */
            play_count?: number | null;
            /** File Path */
            file_path?: string | null;
            /** File Name */
            file_name?: string | null;
            /** File Type */
            file_type?: number | null;
            /** Bitrate */
            bitrate?: number | null;
            /** Sample Rate */
            sample_rate?: number | null;
            /** Release Year */
            release_year?: number | null;
            /** Release Date */
            release_date?: string | null;
            /** Date Added */
            date_added?: string | null;
            /** Artwork Hash */
            artwork_hash?: string | null;
            /**
             * Source
             * @default local
             */
            source: string;
            /**
             * App Play Count
             * @default 0
             */
            app_play_count: number;
            /** Updated At */
            updated_at?: string | null;
            /**
             * Cues
             * @default []
             */
            cues: components["schemas"]["Cue"][];
            /**
             * My Tags
             * @default []
             */
            my_tags: components["schemas"]["MyTag"][];
            /**
             * Playlists
             * @default []
             */
            playlists: components["schemas"]["PlaylistRef"][];
            /**
             * History
             * @default []
             */
            history: components["schemas"]["HistoryEntryOut"][];
            /**
             * Transitions Out
             * @default []
             */
            transitions_out: components["schemas"]["TransitionStatOut"][];
            /**
             * Transitions In
             * @default []
             */
            transitions_in: components["schemas"]["TransitionStatOut"][];
            /**
             * Sets
             * @default []
             */
            sets: components["schemas"]["SetRef"][];
        };
        /** TrackListResponse */
        TrackListResponse: {
            /** Items */
            items: components["schemas"]["TrackOut"][];
            /** Total */
            total: number;
        };
        /** TrackOut */
        TrackOut: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Mix */
            mix?: string | null;
            /** Artist */
            artist?: string | null;
            /** Original Artist */
            original_artist?: string | null;
            /** Remixer */
            remixer?: string | null;
            /** Composer */
            composer?: string | null;
            /** Album */
            album?: string | null;
            /** Genre */
            genre?: string | null;
            /** Label */
            label?: string | null;
            /** Key Name */
            key_name?: string | null;
            /** Camelot */
            camelot?: string | null;
            /** Bpm */
            bpm?: number | null;
            /** Length S */
            length_s?: number | null;
            /** Rating */
            rating?: number | null;
            /** Color */
            color?: string | null;
            /** Comment */
            comment?: string | null;
            /** Play Count */
            play_count?: number | null;
            /** File Path */
            file_path?: string | null;
            /** File Name */
            file_name?: string | null;
            /** File Type */
            file_type?: number | null;
            /** Bitrate */
            bitrate?: number | null;
            /** Sample Rate */
            sample_rate?: number | null;
            /** Release Year */
            release_year?: number | null;
            /** Release Date */
            release_date?: string | null;
            /** Date Added */
            date_added?: string | null;
            /** Artwork Hash */
            artwork_hash?: string | null;
            /**
             * Source
             * @default local
             */
            source: string;
            /**
             * App Play Count
             * @default 0
             */
            app_play_count: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /** TrackSummary */
        TrackSummary: {
            /** Id */
            id: string;
            /** Title */
            title?: string | null;
            /** Mix */
            mix?: string | null;
            /** Artist */
            artist?: string | null;
            /** Bpm */
            bpm?: number | null;
            /** Camelot */
            camelot?: string | null;
            /** Artwork Hash */
            artwork_hash?: string | null;
        };
        /** TransitionOut */
        TransitionOut: {
            /** Id */
            id: number;
            /** From Track Id */
            from_track_id?: string | null;
            /** To Track Id */
            to_track_id?: string | null;
            /** From Entry Id */
            from_entry_id?: number | null;
            /** To Entry Id */
            to_entry_id?: number | null;
            /** Played At */
            played_at?: string | null;
            /**
             * Favorite
             * @default false
             */
            favorite: boolean;
            /** Rating */
            rating?: number | null;
            /** Comment */
            comment?: string | null;
            from_track?: components["schemas"]["TrackSummary"] | null;
            to_track?: components["schemas"]["TrackSummary"] | null;
        };
        /** TransitionPatch */
        TransitionPatch: {
            /** Favorite */
            favorite?: boolean | null;
            /** Rating */
            rating?: number | null;
            /** Comment */
            comment?: string | null;
        };
        /** TransitionStatOut */
        TransitionStatOut: {
            other_track: components["schemas"]["TrackSummary"] | null;
            /** Count */
            count: number;
            /** Fav Count */
            fav_count: number;
            /** Avg Rating */
            avg_rating?: number | null;
            /** Last Comment */
            last_comment?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    sync_state_api_sync_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStateResponse"];
                };
            };
        };
    };
    sync_batch_api_sync_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncBatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_ids_api_sync_ids_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdSet"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdSetResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artwork_get_api_artwork__sha256__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artwork_put_api_artwork__sha256__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artwork_head_api_artwork__sha256__head: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tracks_api_tracks_get: {
        parameters: {
            query?: {
                q?: string | null;
                bpm_min?: number | null;
                bpm_max?: number | null;
                camelot?: string | null;
                genre?: string | null;
                my_tag?: string | null;
                playlist?: string | null;
                rating_min?: number | null;
                added_from?: string | null;
                added_to?: string | null;
                play_count_min?: number | null;
                play_count_max?: number | null;
                source?: string | null;
                never_played?: boolean;
                include_deleted?: boolean;
                sort?: string;
                order?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    track_detail_api_tracks__track_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compatible_tracks_api_tracks__track_id__compatible_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                track_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    facets_api_facets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Facets"];
                };
            };
        };
    };
    history_sessions_api_history_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"][];
                };
            };
        };
    };
    history_session_api_history_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_events_api_agent_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayEvent"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_live_state_api_live_state_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveState"];
                };
            };
        };
    };
    get_auto_record_api_live_auto_record_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoRecordOut"];
                };
            };
        };
    };
    put_auto_record_api_live_auto_record_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoRecordOut"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoRecordOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_ping_api_agent_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_sets_api_sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"][];
                };
            };
        };
    };
    start_set_api_sets_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_set_api_sets__set_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_set_api_sets__set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_set_api_sets__set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_set_api_sets__set_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_entry_api_sets__set_id__entries__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                set_id: number;
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_transition_api_transitions__transition_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transition_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransitionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_rb_api_sets_import_rb__history_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                history_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_rb_all_api_sets_import_rb_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportAllResult"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
